AWSTemplateFormatVersion: "2010-09-09" 
 
 
Resources: 
  ArtifactBucket: 
    Type: AWS::S3::Bucket 
    DeletionPolicy: Retain 
 
  PipelineInfra:  
    Type: AWS::CodePipeline::Pipeline 
    Properties: 
      RoleArn: !GetAtt PipelineRoleTeste.Arn
      Name: !Ref AWS::StackName 
      ArtifactStore: 
        Type: S3 
        Location: !Ref ArtifactBucket 
      Stages:  
        - Name: Source 
          Actions: 
            - Name: Source 
              ActionTypeId: 
                Category: Source 
                Owner: AWS 
                Version: "1" 
                Provider: CodeCommit 
              Configuration: 
                BranchName: master 
                RepositoryName: teste 
              OutputArtifacts: 
                - Name: Out-Source 
              RunOrder: 1 
        - Name: Test 
          Actions: 
            - Name: Cfn-Lint 
              ActionTypeId: 
                  Category: Build 
                  Owner: AWS 
                  Version: "1" 
                  Provider: CodeBuild 
              OutputArtifacts: 
                - Name: Out-Cfn-Lint 
              InputArtifacts: 
                - Name: Out-Source 
              Configuration: 
                  ProjectName: !Ref CfnLint 
              RunOrder: 1 
            - Name: Cfn_Nag 
              ActionTypeId: 
                  Category: Build 
                  Owner: AWS 
                  Version: "1" 
                  Provider: CodeBuild 
              OutputArtifacts: 
                - Name: Out-Cfn-Nag 
              InputArtifacts: 
                - Name: Out-Source 
              Configuration: 
                  ProjectName: !Ref CfnNag 
              RunOrder: 1 
        - Name: Deploy 
          Actions: 
            - Name: SonarDB-CreateChangeSet 
              ActionTypeId: 
                Category: Deploy 
                Owner: AWS 
                Provider: CloudFormation 
                Version: "1" 
              Configuration: 
                ActionMode: CHANGE_SET_REPLACE  
                Capabilities: CAPABILITY_IAM 
                StackName: SonarDB 
                ChangeSetName: SonarDB-ChangeSet 
                TemplatePath: !Join [ "::", [ "Out-Source", "templates/infra-sonar-database.yaml"]] 
                RoleArn: !GetAtt PipelineRoleTeste.Arn
              InputArtifacts: 
                - Name: Out-Source 
              RunOrder: 1 
            - Name: SonarDB-ExecuteChangeSet 
              ActionTypeId: 
                Category: Deploy 
                Owner: AWS 
                Provider: CloudFormation 
                Version: '1' 
              Configuration: 
                ActionMode: CHANGE_SET_EXECUTE 
                ChangeSetName: SonarDB-ChangeSet 
                StackName: SonarDB 
                RoleArn: !GetAtt PipelineRoleTeste.Arn
              RunOrder: 2 
            - Name: SonarApp-CreateChangeSet 
              ActionTypeId: 
                Category: Deploy 
                Owner: AWS 
                Provider: CloudFormation 
                Version: "1" 
              Configuration: 
                ActionMode: CHANGE_SET_REPLACE  
                Capabilities: CAPABILITY_IAM 
                StackName: SonarApp
                ChangeSetName: SonarApp-ChangeSet 
                TemplatePath: !Join [ "::", [ "Out-Source", "templates/cluster-ecs-sonar.yaml"]] 
                RoleArn: !GetAtt PipelineRoleTeste.Arn
              InputArtifacts: 
                - Name: Out-Source 
              RunOrder: 3
            - Name: SonarApp-ExecuteChangeSet 
              ActionTypeId: 
                Category: Deploy 
                Owner: AWS 
                Provider: CloudFormation 
                Version: '1' 
              Configuration: 
                ActionMode: CHANGE_SET_EXECUTE 
                ChangeSetName: SonarApp-ChangeSet 
                StackName: SonarApp
                RoleArn: !GetAtt PipelineRoleTeste.Arn
              RunOrder: 4


  CfnLint: 
    Type: AWS::CodeBuild::Project 
    Properties: 
      Description: CFN-Lint  
      Source: 
        Type: CODEPIPELINE 
        BuildSpec: 'buildspec/buildspec-cfn-lint.yml' 
      Environment: 
        Type: LINUX_CONTAINER 
        ComputeType: BUILD_GENERAL1_SMALL 
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/python:latest 
      Artifacts: 
        Type: CODEPIPELINE 
      ServiceRole: !Ref PipelineRoleTeste
      TimeoutInMinutes: 10 
      VpcConfig: 
        VpcId: !ImportValue vpc-sonar-VPCID
        Subnets: 
          - !ImportValue vpc-sonar-PrivateSubnet1
          - !ImportValue vpc-sonar-PrivateSubnet2
        SecurityGroupIds: 
          - !ImportValue vpc-sonar-SgVPCEndpoints
 
  CfnNag: 
    Type: AWS::CodeBuild::Project 
    Properties: 
      Description: CFN_NAG  
      Source: 
        Type: CODEPIPELINE 
        BuildSpec: 'buildspec/buildspec-cfn_nag.yml' 
      Environment: 
        Type: LINUX_CONTAINER 
        ComputeType: BUILD_GENERAL1_SMALL 
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/ruby:latest 
      Artifacts: 
        Type: CODEPIPELINE 
      ServiceRole: !Ref PipelineRoleTeste
      TimeoutInMinutes: 10 
      VpcConfig: 
        VpcId: !ImportValue vpc-sonar-VPCID
        Subnets: 
          - !ImportValue vpc-sonar-PrivateSubnet1
          - !ImportValue vpc-sonar-PrivateSubnet2
        SecurityGroupIds: 
          - !ImportValue vpc-sonar-SgVPCEndpoints
 
  PipelineRoleTeste: 
    Type: AWS::IAM::Role 
    Properties: 
      RoleName: PipelineRoleTeste
      AssumeRolePolicyDocument: 
        Version: 2012-10-17 
        Statement: 
          - 
            Effect: Allow 
            Principal: 
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
              Service: 
                - "codepipeline.amazonaws.com"
                - "codebuild.amazonaws.com"
                - "cloudformation.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/" 
      Policies: 
        - 
          PolicyName: PipelinePolicyTeste
          PolicyDocument: 
            Version: 2012-10-17 
            Statement: 
              - 
                Effect: Allow 
                Resource: 
                  - "*" 
                Action: 
                  - elasticloadbalancing:*
                  - application-autoscaling:*
                  - codepipeline:* 
                  - cloudformation:*
                  - cloudwatch:* 
                  - events:* 
                  - rds:*
                  - secretsmanager:*
                  - ecr:* 
                  - ecs:* 
                  - ec2:*
                  - s3:*
                  - iam:* 
                  - logs:* 
                  - codecommit:*
                  - autoscaling:* 
                  - codebuild:BatchGetBuilds 
                  - codebuild:StartBuild 
                  - iam:PassRole 
                  - iam:ListRoles 
                  - ssm:GetParameters
                  - ssm:PutParameter
                  - ssm:AddTagsToResource
                  - kms:Encrypt 
                  - kms:Decrypt 
                  - kms:ReEncrypt* 
                  - kms:GenerateDataKey* 
                  - kms:DescribeKey 
